export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";
export const AUTH_LOADING_START = "AUTH_LOADING_START";
export const AUTH_LOADING_END = "AUTH_LOADING_END";

export const SIGNUP = "SIGNUP";
export const SIGNIN = "SIGNIN";
export const SIGNOUT = "SIGNOUT";

export const FETCH_RECIPES = "FETCH_RECIPES";
export const FETCH_RECIPES_BY_CATEGORY = "FETCH_RECIPES_BY_CATEGORY";
export const FETCH_RECIPES_BY_SEARCH = "FETCH_RECIPES_BY_SEARCH";
export const FETCH_DROPDOWN_CATEGORIES = "FETCH_DROPDOWN_CATEGORIES";
export const FETCH_RECIPE = "FETCH_RECIPE";
export const CREATE_RECIPE = "CREATE_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
